-- liquibase formatted sql

-- changeset vyacheslav:1

create table group_participant
(
    group_id       bigint not null,
    participant_id bigint not null
);

create table groups
(
    cost_limit          float4 not null,
    end_of_registration timestamp(6),
    exchange_of_gifts   timestamp(6),
    id                  bigint generated by default as identity,
    name_group          varchar(255),
    primary key (id)
);

create table participants
(
    id         bigint not null,
    first_name varchar(255),
    last_name  varchar(255),
    primary key (id)
);

alter table if exists group_participant
    add constraint key1
    foreign key (participant_id)
    references participants;

alter table if exists group_participant
    add constraint key2
    foreign key (group_id)
    references groups;